[theme]
base="dark"
primaryColor="#2E86C1"
font="sans serif"

[server]
# Enable detailed error messages in the browser
showErrorDetails = false

[browser]
# Enable gathering usage statistics globally (if deployed)
gatherUsageStats = false
